const months = Array.from({ length: 12 }, (_, i) => `Mes ${i + 1}`);
const quarters = ["1Q", "2Q", "3Q", "4Q"];
const exampleState = {
  meta: { project: "Plan de Marketing Digital", team: "Equipo 1", date: new Date().toISOString().slice(0, 10), arpu: 2000, wacc: 0.08, riskPremium: 0.05, kValue: 0.007, annualPurchases: 1.2, conversion: 0.03, retentionBase: 0.05, retentionStrategy: 0.1, ltvOpexRate: 0.15, initialCustomers: 1000 },
  audience: [0, 0, 0, 0, 0, 525, 685, 1200, 1750, 1560, 1320, 1456],
  revenueRows: [
    { channel: "Trafico trimestre", description: "Usuarios web", unit: "usuarios", q: [22461, 23584, 24763, 26001] },
    { channel: "BBDD", description: "Leads propios", unit: "leads", q: [500, 750, 1000, 750] },
    { channel: "SEM", description: "Clientes captados", unit: "EUR", q: [4492, 11792, 6191, 1300] },
    { channel: "SEO", description: "Clientes captados", unit: "EUR", q: [0, 2358, 2476, 13001] },
    { channel: "MGM", description: "Programa referidos", unit: "EUR", q: [2500, 3750, 5000, 3750] },
    { channel: "RRSS", description: "Fans / social", unit: "EUR", q: [8423, 8844, 15787, 24701] }
  ],
  opexRows: [
    { concept: "Usabilidad", description: "Coste por jornada", unitCost: 300, units: 180, q: [27000, 27000, 0, 0] },
    { concept: "SEM", description: "CPC", unitCost: 1.2, units: 2597, q: [1078, 1132, 594, 312] },
    { concept: "MGM", description: "Fee a referentes", unitCost: 60, units: 60, q: [600, 900, 1200, 900] },
    { concept: "MGM", description: "Creatividad", unitCost: 1000, units: 1, q: [1000, 0, 0, 0] },
    { concept: "RRSS", description: "Community manager", unitCost: 30, units: 231, q: [1011, 1061, 1894, 2964] },
    { concept: "Mantenimiento", description: "% sobre inversion", unitCost: 0.1, units: 4262, q: [1065, 1065, 1065, 1065] }
  ],
  capexRows: [
    { category: "Software servidor", concept: "Sistema operativo servidor", unit: "Licencias", units: 1, unitInvestment: 639 },
    { category: "Software servidor", concept: "Base de datos", unit: "Terabytes", units: 1, unitInvestment: 100 },
    { category: "Software servidor", concept: "Application Server", unit: "Licencias", units: 1, unitInvestment: 420 },
    { category: "Hardware servidor", concept: "Servidores", unit: "Maquinas + config", units: 1, unitInvestment: 2500 },
    { category: "Hardware servidor", concept: "Almacenamiento", unit: "Disco TB", units: 1, unitInvestment: 167 },
    { category: "Hardware servidor", concept: "Equipos de red", unit: "LAN + otros", units: 1, unitInvestment: 991 },
    { category: "Desarrollo", concept: "SEO", unit: "Persona-jornada", units: 50, unitInvestment: 120 },
    { category: "Desarrollo", concept: "MGM-LP", unit: "Persona-jornada", units: 50, unitInvestment: 200 },
    { category: "Desarrollo", concept: "MGM-BBDD", unit: "Persona-jornada", units: 25, unitInvestment: 320 },
    { category: "Desarrollo", concept: "RRSS-LP", unit: "Persona-jornada", units: 25, unitInvestment: 300 }
  ],
  kai: { phi: 0.82, usability: 0.76, frequency: 0.64, dataActivation: 0.7, networkIndex: 0.58, cc: 0.74, abcd: 0.62, nps: 0.68, purpose: 0.8, context: 0.9, monetization: 125000, cost: 42000 },
  notes: "Caso docente para estimar si la campana sostiene su inversion, mejora el valor del cliente y crea equity activo."
};
let state = loadState();
let currentStep = 0;
const steps = [
  ["Contexto ejecutivo", "Empieza por el marco de decision. No buscamos una cifra perfecta; buscamos una hipotesis defendible ante un comite.", "Piensa en esta pantalla como la portada del caso: que proyecto se evalua, que equipo lo defiende y que variables financieras mandan.", renderContext],
  ["Audiencia y conversion", "Aqui traduces mercado, cartera o trafico en clientes objetivo. La conversion no es un deseo: debe ser una hipotesis razonada.", "Si alguien cuestiona la conversion, que evidencia o benchmark podrias mostrar?", renderAudience],
  ["Ingresos por canal", "Ordena de donde viene el valor. Cada canal debe explicar que aporta y cuando se espera capturar ese valor.", "No mezcles actividad con ingreso. Aqui solo vale lo que ayuda a sostener el caso.", () => renderQuarterTable("revenueRows")],
  ["OPEX: coste de operar", "El OPEX recoge lo que cuesta ejecutar, mantener y sostener la campana.", "Si el proyecto triunfa, que costes crecen con el? Pon una hipotesis visible para discutirla.", () => renderQuarterTable("opexRows")],
  ["CAPEX: inversion inicial", "El CAPEX es la inversion que permite arrancar: tecnologia, desarrollo, infraestructura, formacion o compliance.", "Cuanto dinero hay que poner antes de que el proyecto empiece a devolver valor?", renderCapex],
  ["LTV y cartera", "El LTV mira mas alla de la venta inmediata: cuanto valor deja un cliente cuando conseguimos retenerlo mejor.", "La diferencia entre retencion sin estrategia y con estrategia es una promesa. Hazla ambiciosa, pero no fantasiosa.", renderLtv],
  ["Customer Equity Activo", "KAI ROI ayuda a explicar que la confianza, el dato, la relacion y el contexto tambien pesan en la creacion de valor.", "Pasa de ROI financiero a conversacion estrategica: que capacidad tiene la organizacion para convertir relacion en valor?", renderEquity],
  ["Resultado explicado", "El cierre traduce el modelo en indicadores que un C-level puede leer rapido y un alumno puede defender con criterio.", "Un buen resultado no es solo un numero verde. Es una decision: invertir, optimizar o redisenar.", renderFinal]
];
function loadState() { try { return JSON.parse(localStorage.getItem("docroi-state")) || structuredClone(exampleState); } catch { return structuredClone(exampleState); } }
function saveState() { localStorage.setItem("docroi-state", JSON.stringify(state)); }
function n(v) { const x = Number(String(v).replace(",", ".")); return Number.isFinite(x) ? x : 0; }
function sum(v) { return v.reduce((a, b) => a + n(b), 0); }
function money(v) { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(n(v)); }
function pct(v) { return new Intl.NumberFormat("es-ES", { style: "percent", maximumFractionDigits: 1 }).format(n(v)); }
function num(v) { return new Intl.NumberFormat("es-ES", { maximumFractionDigits: 2 }).format(n(v)); }
function calculate() {
  const m = state.meta;
  const clients = state.audience.map(a => a * n(m.conversion));
  const monthlyRevenue = clients.map(c => c * n(m.arpu));
  const opexQ = quarters.map((_, i) => sum(state.opexRows.map(r => r.q[i])));
  const monthlyOpex = months.map((_, i) => opexQ[Math.floor(i / 3)] / 3);
  const capex = sum(state.capexRows.map(r => n(r.units) * n(r.unitInvestment)));
  const cashFlow = monthlyRevenue.map((r, i) => r - monthlyOpex[i] - (i === 0 ? capex : 0));
  const accumulated = cashFlow.reduce((a, v, i) => (a.push(v + (a[i - 1] || 0)), a), []);
  const totalRevenue = sum(monthlyRevenue), totalOpex = sum(monthlyOpex), netProfit = sum(cashFlow);
  const roi = capex ? netProfit / capex : 0;
  const rate = Math.pow(1 + n(m.wacc), 1 / 12) - 1;
  const van = cashFlow.reduce((t, v, i) => t + v / Math.pow(1 + rate, i + 1), 0);
  const paybackIndex = accumulated.findIndex(v => v >= 0);
  return { clients, monthlyRevenue, monthlyOpex, capex, cashFlow, accumulated, totalRevenue, totalOpex, netProfit, roi, van, payback: paybackIndex >= 0 ? paybackIndex + 1 : null, roiCe: capex ? (totalRevenue - totalOpex) / capex : 0, roiPure: roi - n(m.wacc), ltv: calculateLtv(), kai: calculateKai() };
}
function calculateLtv() {
  const m = state.meta, avg = n(m.arpu) * n(m.annualPurchases);
  const scenario = retention => { let customers = n(m.initialCustomers), cumulative = 0; return [0,1,2,3,4].map(year => { if (year > 0) customers *= n(retention); const revenue = customers * avg, costs = revenue * n(m.ltvOpexRate), margin = revenue - costs, discounted = margin / Math.pow(1 + n(m.wacc), year); cumulative += discounted; return { year: year + 1, customers, revenue, costs, margin, discounted, cumulative, ltv: cumulative / Math.max(n(m.initialCustomers), 1) }; }); };
  const base = scenario(m.retentionBase), strategy = scenario(m.retentionStrategy), baseLtv = base.at(-1).ltv, strategyLtv = strategy.at(-1).ltv;
  return { averageSale: avg, base, strategy, baseLtv, strategyLtv, differential: strategyLtv - baseLtv, totalImpact: (strategyLtv - baseLtv) * n(m.initialCustomers) };
}
function calculateKai() {
  const k = state.kai, psi = (n(k.dataActivation) + n(k.networkIndex)) / 2, spo = n(k.cc) * n(k.abcd) * n(k.nps);
  const kaiStar = n(k.phi) * n(k.usability) * n(k.frequency) * psi * spo * n(k.purpose) * n(k.context);
  const cost = Math.max(n(k.cost), 1), ce = ((((kaiStar * n(k.monetization)) - cost) / cost) - n(state.meta.wacc)) / Math.max(n(state.meta.wacc), 0.0001);
  return { psi, spo, kaiStar, ce };
}
function input(path, label, help, type = "number") { const value = path.split(".").reduce((o, k) => o[k], state); const id = path.replaceAll(".", "-"); return `<div class="field"><label for="${id}">${label}</label><input id="${id}" data-path="${path}" type="${type}" value="${value}"><small>${help}</small></div>`; }
function renderContext() { return `<div class="field-grid">${input("meta.project", "Nombre del proyecto", "Ejemplo: Plan de Marketing Digital para captacion de alumnos.", "text")}${input("meta.team", "Equipo responsable", "Quien firma las hipotesis y defendera el caso.", "text")}${input("meta.date", "Fecha del caso", "Sirve para fijar la version de los supuestos.", "date")}${input("meta.arpu", "Ingreso medio por cliente / ARPU", "Cuanto factura de media un cliente o alumno captado.")}${input("meta.wacc", "WACC anual", "Coste de capital. El liston minimo que debe superar el proyecto. 0,08 significa 8 %.")}${input("meta.riskPremium", "Prima de riesgo", "Colchon para reconocer incertidumbre de mercado, ejecucion o datos.")}${input("meta.kValue", "Valor K", "Coeficiente docente de sensibilidad.")}<div class="field full"><label for="notes">Narrativa del caso</label><textarea id="notes" data-path="notes" rows="4">${state.notes}</textarea><small>Escribe que se quiere probar y por que importa para negocio.</small></div></div>`; }
function renderAudience() { return `<div class="field-grid">${input("meta.conversion", "Conversion objetivo", "Porcentaje de audiencia que esperas convertir. 0,03 significa 3 %.")}${input("meta.initialCustomers", "Cartera inicial LTV", "Base de clientes para valorar la mejora de relacion y retencion.")}</div><table class="editable-table"><thead><tr>${months.map(m => `<th>${m}</th>`).join("")}</tr></thead><tbody><tr>${state.audience.map((v, i) => `<td><input data-array="audience" data-index="${i}" type="number" value="${v}"></td>`).join("")}</tr></tbody></table>`; }
function tableInput(kind, row, key, value, type = "number") { return `<input data-table="${kind}" data-row="${row}" data-key="${key}" type="${type}" value="${value}">`; }
function renderQuarterTable(kind) { const isRevenue = kind === "revenueRows"; const headers = isRevenue ? ["Canal", "Descripcion", "Unidad", ...quarters, "Total"] : ["Concepto", "Descripcion", "Coste unidad", "Unidades", ...quarters, "Total"]; const rows = state[kind].map((r, i) => { const left = isRevenue ? [tableInput(kind, i, "channel", r.channel, "text"), tableInput(kind, i, "description", r.description, "text"), tableInput(kind, i, "unit", r.unit, "text")] : [tableInput(kind, i, "concept", r.concept, "text"), tableInput(kind, i, "description", r.description, "text"), tableInput(kind, i, "unitCost", r.unitCost), tableInput(kind, i, "units", r.units)]; return `<tr>${left.map(x => `<td>${x}</td>`).join("")}${r.q.map((v, q) => `<td><input data-quarter="${kind}" data-row="${i}" data-q="${q}" type="number" value="${v}"></td>`).join("")}<td><strong>${money(sum(r.q))}</strong></td></tr>`; }).join(""); return `<table class="editable-table"><thead><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><div class="table-actions"><button class="ghost-action" type="button" data-add-row="${kind}">Anadir linea</button></div>`; }
function renderCapex() { return `<table class="editable-table"><thead><tr><th>Categoria</th><th>Concepto</th><th>Unidad</th><th>Unidades</th><th>Inversion unidad</th><th>CAPEX</th></tr></thead><tbody>${state.capexRows.map((r, i) => `<tr><td>${tableInput("capexRows", i, "category", r.category, "text")}</td><td>${tableInput("capexRows", i, "concept", r.concept, "text")}</td><td>${tableInput("capexRows", i, "unit", r.unit, "text")}</td><td>${tableInput("capexRows", i, "units", r.units)}</td><td>${tableInput("capexRows", i, "unitInvestment", r.unitInvestment)}</td><td><strong>${money(n(r.units) * n(r.unitInvestment))}</strong></td></tr>`).join("")}</tbody></table><div class="table-actions"><button class="ghost-action" type="button" data-add-row="capexRows">Anadir inversion</button></div>`; }
function renderLtv() { const r = calculate().ltv; return `<div class="field-grid">${input("meta.annualPurchases", "Compra media anual por cliente", "Compras o matriculas equivalentes por ano.")}${input("meta.retentionBase", "Retencion sin estrategia", "Cuanto cliente queda si no haces nada especial.")}${input("meta.retentionStrategy", "Retencion con estrategia", "Cuanto cliente esperas conservar gracias al plan.")}${input("meta.ltvOpexRate", "% coste OPEX para LTV", "Parte de los ingresos que consume operar el cliente.")}</div><div class="explainer-grid"><div class="explainer"><span>LTV sin estrategia</span><strong>${money(r.baseLtv)}</strong></div><div class="explainer"><span>LTV con estrategia</span><strong>${money(r.strategyLtv)}</strong></div><div class="explainer"><span>Impacto total cartera</span><strong>${money(r.totalImpact)}</strong></div></div>`; }
function renderEquity() { const k = calculate().kai; return `<div class="formula-block"><code>KAIi* = phi_i * u_i * f_i * psi_i * SPO_i * P_i * Gamma_g(i),t</code><code>CE_i = ((((KAIi* * MD_i) - C_i) / C_i) - WACC_t) / WACC_t</code></div><div class="field-grid">${input("kai.phi", "phi: confianza base", "De 0 a 1. Confianza inicial en la marca o institucion.")}${input("kai.usability", "u: facilidad de uso", "De 0 a 1. Si el camino es facil, el valor fluye mejor.")}${input("kai.frequency", "f: frecuencia de relacion", "De 0 a 1. Mide si la relacion se sostiene.")}${input("kai.dataActivation", "DataActivation", "De 0 a 1. Si el dato sirve para actuar.")}${input("kai.networkIndex", "I_net", "De 0 a 1. Capacidad de expandirse por red o recomendacion.")}${input("kai.cc", "CC: confianza/comunidad", "De 0 a 1. Calidad relacional observable.")}${input("kai.abcd", "ABCD: comportamiento", "De 0 a 1. Senales de uso, accion o compromiso.")}${input("kai.nps", "NPS normalizado", "De 0 a 1. Recomendacion en escala comparable.")}${input("kai.purpose", "P: coherencia de proposito", "De 0 a 1. Encaje con lo que la institucion dice ser.")}${input("kai.context", "Gamma: contexto", "De 0 a 1 o mas. Ajusta mercado, momento o cultura.")}${input("kai.monetization", "MD: monetizacion observable", "Ingreso o valor atribuible al segmento.")}${input("kai.cost", "C: coste atribuible", "Coste total para crear ese valor.")}</div><div class="explainer-grid"><div class="explainer"><span>psi</span><strong>${num(k.psi)}</strong><p>Dato activado: saber algo y usarlo bien.</p></div><div class="explainer"><span>SPO</span><strong>${num(k.spo)}</strong><p>Relacion: confianza, comportamiento y recomendacion juntos.</p></div><div class="explainer"><span>CE_i</span><strong>${num(k.ce)}</strong><p>Si es positivo, el valor supera coste y coste de capital.</p></div></div>`; }
function renderFinal() { const r = calculate(); return `<div class="plain-note"><strong>${decisionText(r).title}</strong><p>${decisionText(r).body}</p></div>${renderKpiExplain(r)}`; }
function renderCurrentStep() { const s = steps[currentStep]; document.getElementById("stepCounter").textContent = `Paso ${currentStep + 1} de ${steps.length}`; document.getElementById("completionHint").textContent = `${Math.round(((currentStep + 1) / steps.length) * 100)} % completado`; document.getElementById("stepContent").innerHTML = `<h2 class="step-title">${currentStep + 1}. ${s[0]}</h2><p class="step-intro">${s[1]}</p><div class="reflection"><strong>Reflexion:</strong> ${s[2]}</div>${s[3]()}`; document.getElementById("prevStep").disabled = currentStep === 0; document.getElementById("nextStep").textContent = currentStep === steps.length - 1 ? "Actualizar informe" : "Siguiente"; bindInputs(); renderNav(); }
function renderNav() { document.getElementById("stepNav").innerHTML = steps.map((s, i) => `<button type="button" class="${i === currentStep ? "active" : ""}" data-step="${i}"><span class="step-number">${i + 1}</span><span>${s[0]}</span></button>`).join(""); }
function bindInputs() { document.querySelectorAll("[data-path]").forEach(e => e.addEventListener("input", () => { const keys = e.dataset.path.split("."), last = keys.pop(), target = keys.reduce((o, k) => o[k], state); target[last] = e.type === "number" ? n(e.value) : e.value; changed(); })); document.querySelectorAll("[data-array='audience']").forEach(e => e.addEventListener("input", () => { state.audience[Number(e.dataset.index)] = n(e.value); changed(); })); document.querySelectorAll("[data-table]").forEach(e => e.addEventListener("input", () => { const row = state[e.dataset.table][Number(e.dataset.row)]; row[e.dataset.key] = e.type === "number" ? n(e.value) : e.value; changed(false); })); document.querySelectorAll("[data-quarter]").forEach(e => e.addEventListener("input", () => { state[e.dataset.quarter][Number(e.dataset.row)].q[Number(e.dataset.q)] = n(e.value); changed(false); })); document.querySelectorAll("[data-add-row]").forEach(b => b.addEventListener("click", () => { addRow(b.dataset.addRow); changed(true); })); }
function addRow(kind) { if (kind === "capexRows") state.capexRows.push({ category: "Otros", concept: "Nuevo concepto", unit: "Proyecto", units: 1, unitInvestment: 0 }); else if (kind === "revenueRows") state.revenueRows.push({ channel: "Nuevo canal", description: "Hipotesis de ingreso", unit: "EUR", q: [0,0,0,0] }); else state.opexRows.push({ concept: "Nuevo coste", description: "Coste recurrente", unitCost: 0, units: 0, q: [0,0,0,0] }); }
function changed(rerender = true) { saveState(); renderLive(); renderReport(); if (rerender) renderCurrentStep(); }
function decisionText(r) { if (r.roi >= 0.25) return { status: "status-good", title: "Proyecto atractivo", body: "El ROI supera el 25 %. Por cada euro invertido, el caso devuelve valor suficiente para defenderlo." }; if (r.roi >= 0) return { status: "status-watch", title: "Proyecto viable, pero ajustable", body: "El proyecto devuelve mas de lo que cuesta, aunque conviene optimizar ingresos, OPEX o CAPEX." }; return { status: "status-risk", title: "Proyecto en riesgo", body: "La caja no compensa la inversion. Revisa conversion, ingresos, costes o inversion inicial." }; }
function renderLive() { const r = calculate(), d = decisionText(r); document.getElementById("resultTitle").textContent = d.title; document.getElementById("kpiStrip").innerHTML = [["ROI", pct(r.roi), "Retorno sobre inversion"], ["VAN", money(r.van), "Valor actual neto"], ["Payback", r.payback ? `Mes ${r.payback}` : "No recuperado", "Mes de recuperacion"], ["LTV diferencial", money(r.ltv.differential), "Mejora por cliente"]].map(k => `<div class="kpi-card"><span>${k[0]}</span><strong>${k[1]}</strong><span>${k[2]}</span></div>`).join(""); document.getElementById("executiveRead").innerHTML = `<strong class="${d.status}">${d.title}</strong><p>${d.body}</p>`; renderChart(r.accumulated); }
function renderChart(values) { const max = Math.max(...values.map(v => Math.abs(v)), 1); document.getElementById("barChart").innerHTML = values.map(v => `<div class="bar ${v < 0 ? "negative" : ""}" style="height:${Math.max(4, Math.abs(v) / max * 130)}px" title="${money(v)}"></div>`).join(""); }
function renderKpiExplain(r) { const rows = [["ROI", pct(r.roi), "Mide si el proyecto devuelve mas dinero del que pide para arrancar."], ["VAN", money(r.van), "Trae el dinero futuro al valor de hoy."], ["Payback", r.payback ? `Mes ${r.payback}` : "No recuperado", "Dice cuando recuperas lo invertido."], ["Beneficio neto", money(r.netProfit), "Lo que queda despues de ingresos, OPEX y CAPEX."], ["ROI CE", pct(r.roiCe), "Retorno antes de descontar la inversion inicial."], ["ROI puro - WACC", pct(r.roiPure), "Compara el ROI con el liston minimo del capital."], ["LTV diferencial", money(r.ltv.differential), "Valor extra por cliente cuando mejora la retencion."], ["Impacto total LTV", money(r.ltv.totalImpact), "Mejora por cliente multiplicada por la cartera."], ["KAI*", num(r.kai.kaiStar), "Capacidad de convertir confianza, dato, relacion y contexto en valor."], ["Customer Equity CE_i", num(r.kai.ce), "Resultado economico ajustado por coste y WACC."]]; return `<table class="result-table"><thead><tr><th>KPI</th><th>Resultado</th><th>Como leerlo</th></tr></thead><tbody>${rows.map(x => `<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join("")}</tbody></table>`; }
function renderReport() { const r = calculate(), d = decisionText(r); document.getElementById("reportMeta").textContent = `${state.meta.project} - ${state.meta.team} - ${state.meta.date}`; const monthly = months.map((m, i) => `<tr><td>${m}</td><td>${money(r.monthlyRevenue[i])}</td><td>${money(r.monthlyOpex[i])}</td><td>${money(r.cashFlow[i])}</td><td>${money(r.accumulated[i])}</td></tr>`).join(""); document.getElementById("reportBody").innerHTML = `<section class="report-section"><h3>Lectura ejecutiva</h3><p><strong class="${d.status}">${d.title}.</strong> ${d.body}</p><p>${state.notes}</p></section><section class="report-section"><h3>Indicadores explicados</h3>${renderKpiExplain(r)}</section><section class="report-section"><h3>Customer Equity Activo</h3><p>KAI ROI ordena dato, confianza, relacion, contexto y retorno economico. No sustituye al ROI: lo complementa para explicar si la organizacion convierte relacion en valor sostenible.</p><div class="formula-block"><code>KAIi* = phi_i * u_i * f_i * psi_i * SPO_i * P_i * Gamma_g(i),t</code><code>CE_i = ((((KAIi* * MD_i) - C_i) / C_i) - WACC_t) / WACC_t</code></div></section><section class="report-section"><h3>Resumen mensual</h3><table class="result-table"><thead><tr><th>Mes</th><th>Ingresos</th><th>OPEX</th><th>Cash flow</th><th>Acumulado</th></tr></thead><tbody>${monthly}</tbody></table></section>`; }
document.getElementById("prevStep").addEventListener("click", () => { currentStep = Math.max(0, currentStep - 1); renderCurrentStep(); });
document.getElementById("nextStep").addEventListener("click", () => { currentStep = Math.min(steps.length - 1, currentStep + 1); renderCurrentStep(); });
document.getElementById("stepNav").addEventListener("click", e => { const b = e.target.closest("button[data-step]"); if (!b) return; currentStep = Number(b.dataset.step); renderCurrentStep(); });
document.getElementById("printReport").addEventListener("click", () => { renderReport(); window.print(); });
document.getElementById("resetExample").addEventListener("click", () => { state = structuredClone(exampleState); saveState(); renderCurrentStep(); renderLive(); renderReport(); });
renderCurrentStep();
renderLive();
renderReport();
